import {
  Document,
  Packer,
  Paragraph,
  Table,
  TableRow,
  TableCell,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  WidthType,
  ShadingType,
  Header,
  Footer,
} from "docx";
import { saveAs } from "file-saver";

interface ExtractedField {
  label: string;
  value: string;
  confidence?: string;
  confidencePercentage?: number;
  sourceDoc?: string;
  evidenceSnippets?: { text: string; source: string; page?: number }[];
}

interface DocumentInfo {
  name: string;
  path?: string;
  ocrScore?: number;
  quality?: string;
}

interface IIBEntry {
  policy_no: string;
  company: string;
  sum_assured: string;
  match_status: string;
  reason: string;
  effective_date: string;
  product_type: string;
  medical_flag: string;
  standard_life: string;
  reason_decline: string;
  reason_postpone: string;
  reason_repudiation: string;
}

interface CaseData {
  id: string;
  policyNumber?: string;
  applicantName: string;
  age?: number;
  gender?: string;
  education?: string;
  occupation?: string;
  sumAssured: string;
  premium: string;
  product?: string;
  channel?: string;
  drcScore?: string;
  nominee?: string;
  uwSummary?: string;
  financialInfo?: ExtractedField[];
  medicalInfo?: ExtractedField[];
  documents?: DocumentInfo[];
  createdDate?: string;
  updatedBy?: string;
  auditLogs?: { timestamp: string; user: string; action: string }[];
  iib?: IIBEntry[];
}

interface ExportOptions {
  caseData: CaseData;
  userName: string;
  starRating?: number;
  flags?: string[];
  caseUrl?: string;
}

const borderStyle = {
  top: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
  bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
  left: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
  right: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
};

const createHeaderCell = (text: string, width?: number) =>
  new TableCell({
    children: [
      new Paragraph({
        children: [new TextRun({ text, bold: true, size: 20 })],
      }),
    ],
    shading: { type: ShadingType.SOLID, color: "F5F5F5" },
    borders: borderStyle,
    width: width ? { size: width, type: WidthType.PERCENTAGE } : undefined,
  });

const createCell = (text: string, highlight?: boolean, width?: number) =>
  new TableCell({
    children: [
      new Paragraph({
        children: [new TextRun({ text, size: 20 })],
      }),
    ],
    shading: highlight ? { type: ShadingType.SOLID, color: "FFFDE7" } : undefined,
    borders: borderStyle,
    width: width ? { size: width, type: WidthType.PERCENTAGE } : undefined,
  });

const rulesData = [
  {
    id: "ITR_COUNT_CHECK",
    desc: "Minimum 3 yrs ITRs for self-employed",
    status: "Pass",
    evidence: "3 ITRs found — ITR_2021, ITR_2022, ITR_2023",
    trigger: "-",
  },
  {
    id: "PAN_MATCH",
    desc: "PAN on ITR matches KYC PAN",
    status: "Pass",
    evidence: "PAN match found on ITR p2 and KYC doc",
    trigger: "-",
  },
  {
    id: "INCOME_VERIFY",
    desc: "Income matches declared amount",
    status: "Warning",
    evidence: "Income variance detected — ITR shows ₹2.87Cr vs declared ₹2.55Cr",
    trigger: "INCOME_MISMATCH",
  },
  {
    id: "SIG_VERIFY",
    desc: "Signature consistency across documents",
    status: "Fail",
    evidence: "Specimen signatures in diff styles on medicals",
    trigger: "SIGNATURE_MISMATCH",
  },
  {
    id: "NOM_RELATION",
    desc: "Nominee relationship validation",
    status: "Fail",
    evidence: "Nominee: Mother — unusual for married applicant",
    trigger: "NOMINEE_MISMATCH",
  },
];

export const generateUWSummaryDoc = async (options: ExportOptions): Promise<string> => {
  const { caseData, userName, starRating, flags, caseUrl } = options;
  const timestamp = new Date().toISOString();
  const exportId = `EXP_${Date.now()}`;
  const policyNo = caseData.policyNumber || caseData.id;

  const doc = new Document({
    sections: [
      {
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: "UW AI Assistant — Detailed UW Summary",
                    bold: true,
                    size: 32,
                  }),
                ],
              }),
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: `Policy: ${policyNo} | Applicant: ${caseData.applicantName} | Generated: ${new Date().toLocaleString()}`,
                    size: 18,
                    color: "666666",
                  }),
                ],
              }),
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: `Generated by: ${userName} | Case URL: ${caseUrl || window.location.href}`,
                    size: 16,
                    color: "888888",
                  }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: `Export ID: ${exportId} | Version 1.0 | CONFIDENTIAL — For internal use only`,
                    size: 16,
                    color: "999999",
                  }),
                ],
              }),
            ],
          }),
        },
        children: [
          // Section 1: Case Metadata
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: "1. Case Metadata", bold: true })],
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createCell(`Policy No: ${policyNo}`, false, 50),
                  createCell(`Applicant Name: ${caseData.applicantName}`, false, 50),
                ],
              }),
              new TableRow({
                children: [
                  createCell(`Age/Gender: ${caseData.age || "-"}/${caseData.gender || "-"}`, false, 50),
                  createCell(`Product: ${caseData.product || "-"}`, false, 50),
                ],
              }),
              new TableRow({
                children: [
                  createCell(`Channel: ${caseData.channel || "-"}`, false, 50),
                  createCell(`Sum Assured: ${caseData.sumAssured}`, false, 50),
                ],
              }),
              new TableRow({
                children: [
                  createCell(`Premium: ${caseData.premium}`, false, 50),
                  createCell(`Created: ${caseData.createdDate || "-"}`, false, 50),
                ],
              }),
              new TableRow({
                children: [
                  createCell(`Assigned To: ${caseData.updatedBy || "-"}`, false, 50),
                  createCell(`DRC Score: ${caseData.drcScore || "-"}`, false, 50),
                ],
              }),
            ],
          }),

          // Section 2: AI Summary
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: "2. Executive (AI) Summary", bold: true })],
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: caseData.uwSummary || "No AI summary available.",
                size: 20,
              }),
            ],
            spacing: { after: 200 },
          }),

          // Section 3: Applicant Data Table
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: "3. Applicant Data", bold: true })],
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createHeaderCell("Field", 20),
                  createHeaderCell("Extracted Value", 30),
                  createHeaderCell("Source Doc", 20),
                  createHeaderCell("Page", 10),
                  createHeaderCell("Confidence %", 20),
                ],
              }),
              new TableRow({
                children: [
                  createCell("Name"),
                  createCell(caseData.applicantName),
                  createCell("Identity Verification"),
                  createCell("1"),
                  createCell("94%"),
                ],
              }),
              new TableRow({
                children: [
                  createCell("Age"),
                  createCell(String(caseData.age || "-")),
                  createCell("Identity Verification"),
                  createCell("1"),
                  createCell("94%"),
                ],
              }),
              new TableRow({
                children: [
                  createCell("Nominee"),
                  createCell(caseData.nominee || "-"),
                  createCell("Application Form"),
                  createCell("3"),
                  createCell("88%"),
                ],
              }),
              new TableRow({
                children: [
                  createCell("Occupation"),
                  createCell(caseData.occupation || "-"),
                  createCell("Financial Statements"),
                  createCell("1"),
                  createCell("76%"),
                ],
              }),
            ],
          }),

          // Section 4: Financial Information Table
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: "4. Financial Information", bold: true })],
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createHeaderCell("Field", 18),
                  createHeaderCell("Value", 22),
                  createHeaderCell("Source Doc & Page", 25),
                  createHeaderCell("Confidence", 15),
                  createHeaderCell("Notes", 20),
                ],
              }),
              ...(caseData.financialInfo || []).map(
                (field) =>
                  new TableRow({
                    children: [
                      createCell(field.label),
                      createCell(field.value),
                      createCell(
                        `${field.sourceDoc || "-"} (p${field.evidenceSnippets?.[0]?.page || "-"})`
                      ),
                      createCell(
                        `${field.confidencePercentage || "-"}%`,
                        (field.confidencePercentage || 100) < 70
                      ),
                      createCell(field.evidenceSnippets?.[0]?.text || "-"),
                    ],
                  })
              ),
            ],
          }),

          // Section 5: Medical Information Table
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: "5. Medical Information", bold: true })],
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createHeaderCell("Metric", 18),
                  createHeaderCell("Value", 25),
                  createHeaderCell("Source Doc & Page", 25),
                  createHeaderCell("Confidence", 15),
                  createHeaderCell("Flags", 17),
                ],
              }),
              ...(caseData.medicalInfo || []).map(
                (field) =>
                  new TableRow({
                    children: [
                      createCell(field.label),
                      createCell(field.value),
                      createCell(
                        `${field.sourceDoc || "-"} (p${field.evidenceSnippets?.[0]?.page || "-"})`
                      ),
                      createCell(
                        `${field.confidencePercentage || "-"}%`,
                        (field.confidencePercentage || 100) < 70
                      ),
                      createCell((field.confidencePercentage || 100) < 70 ? "⚠ Low conf" : "-"),
                    ],
                  })
              ),
            ],
          }),

          // Section 6: Documents & Extraction Table
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: "6. Documents & Extraction Details", bold: true })],
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createHeaderCell("Doc Type", 20),
                  createHeaderCell("Filename/ID", 20),
                  createHeaderCell("Key Extractions", 30),
                  createHeaderCell("OCR Conf", 15),
                  createHeaderCell("Missing Pages", 15),
                ],
              }),
              ...(caseData.documents || []).map(
                (doc) =>
                  new TableRow({
                    children: [
                      createCell(doc.name),
                      createCell(doc.path?.split("/").pop() || doc.name),
                      createCell(getKeyExtractionsForDoc(doc.name, caseData)),
                      createCell(`${doc.ocrScore || "-"}%`, (doc.ocrScore || 100) < 70),
                      createCell("No"),
                    ],
                  })
              ),
            ],
          }),

          // Section 7: Rules & Triggers Table
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: "7. Rules Check & Triggers", bold: true })],
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createHeaderCell("Rule ID", 15),
                  createHeaderCell("Description", 25),
                  createHeaderCell("Result", 10),
                  createHeaderCell("Evidence", 35),
                  createHeaderCell("Trigger", 15),
                ],
              }),
              ...rulesData.map(
                (rule) =>
                  new TableRow({
                    children: [
                      createCell(rule.id),
                      createCell(rule.desc),
                      createCell(rule.status, rule.status === "Fail" || rule.status === "Warning"),
                      createCell(rule.evidence),
                      createCell(rule.trigger),
                    ],
                  })
              ),
            ],
          }),

          // Section 8: Confidence & Flags
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: "8. Confidence, Flags & Recommendations", bold: true })],
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "AI Summary Rating: ", bold: true }),
              new TextRun({ text: starRating ? "★".repeat(starRating) + "☆".repeat(5 - starRating) : "Not rated" }),
            ],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Quick Flags: ", bold: true }),
              new TextRun({ text: flags?.length ? flags.join(", ") : "None flagged" }),
            ],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [new TextRun({ text: "Recommended Next Steps:", bold: true })],
            spacing: { after: 50 },
          }),
          new Paragraph({
            children: [new TextRun({ text: "• Request Form 26AS for latest AY", size: 20 })],
            indent: { left: 400 },
          }),
          new Paragraph({
            children: [new TextRun({ text: "• Obtain specimen signatures clarification", size: 20 })],
            indent: { left: 400 },
          }),
          new Paragraph({
            children: [new TextRun({ text: "• Need details and reason for 'Yes' to Q8 in IAR", size: 20 })],
            indent: { left: 400 },
          }),

          // Section 9: Audit & References
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: "9. Audit & References", bold: true })],
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: `Exported by: ${userName}`, size: 20 }),
            ],
            spacing: { after: 50 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: `Time: ${new Date().toLocaleString()}`, size: 20 }),
            ],
            spacing: { after: 50 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: `Case URL: ${caseUrl || window.location.href}`, size: 20 }),
            ],
            spacing: { after: 50 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: `Export ID: ${exportId}`, size: 20 }),
            ],
            spacing: { after: 200 },
          }),

          // Section 10: IIB Information
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: "10. IIB Information", bold: true })],
            spacing: { before: 400, after: 200 },
          }),
          ...generateIIBSection(caseData.iib),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const filename = `UW_Summary_${policyNo}_${caseData.applicantName.replace(/\s+/g, "_")}.docx`;
  saveAs(blob, filename);

  return exportId;
};

function getKeyExtractionsForDoc(docName: string, caseData: CaseData): string {
  const extractions: string[] = [];

  if (docName.includes("Income Tax")) {
    extractions.push(
      `Name: ${caseData.applicantName} (p2)`,
      "PAN: ABCPS1234Q (p2)",
      "Total Income: ₹2,55,00,000 (p6)"
    );
  } else if (docName.includes("Financial")) {
    const income = caseData.financialInfo?.find((f) => f.label === "Annual Income");
    const netWorth = caseData.financialInfo?.find((f) => f.label === "Net Worth");
    if (income) extractions.push(`Income: ${income.value} (p2)`);
    if (netWorth) extractions.push(`Net Worth: ${netWorth.value} (p3)`);
  } else if (docName.includes("Medical")) {
    const bmi = caseData.medicalInfo?.find((m) => m.label === "BMI");
    const bp = caseData.medicalInfo?.find((m) => m.label === "Blood Pressure");
    if (bmi) extractions.push(`BMI: ${bmi.value} (p1)`);
    if (bp) extractions.push(`BP: ${bp.value} (p1)`);
  } else if (docName.includes("Identity")) {
    extractions.push(`Name: ${caseData.applicantName} (p1)`, "PAN verified (p1)");
  }

  return extractions.join("; ") || "-";
}

function generateIIBSection(iibData?: IIBEntry[]): (Paragraph | Table)[] {
  if (!iibData || iibData.length === 0) {
    return [
      new Paragraph({
        children: [
          new TextRun({
            text: "No IIB records available for this applicant.",
            size: 20,
            italics: true,
          }),
        ],
        spacing: { after: 200 },
      }),
    ];
  }

  const elements: (Paragraph | Table)[] = [];

  iibData.forEach((entry, index) => {
    if (iibData.length > 1) {
      elements.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `IIB Record ${index + 1}`,
              bold: true,
              size: 22,
            }),
          ],
          spacing: { before: index > 0 ? 300 : 0, after: 100 },
        })
      );
    }

    const iibFields = [
      { field: "Policy No", value: entry.policy_no },
      { field: "Company", value: entry.company },
      { field: "Sum Assured", value: entry.sum_assured },
      { field: "Match Status", value: entry.match_status },
      { field: "Reason", value: entry.reason },
      { field: "Effective Date", value: entry.effective_date },
      { field: "Product Type", value: entry.product_type },
      { field: "Medical / Non-Medical", value: entry.medical_flag },
      { field: "Standard Life", value: entry.standard_life },
      { field: "Decline Reason", value: entry.reason_decline },
      { field: "Postpone Reason", value: entry.reason_postpone },
      { field: "Repudiation Reason", value: entry.reason_repudiation },
    ];

    elements.push(
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          new TableRow({
            children: [
              createHeaderCell("Field", 40),
              createHeaderCell("Value", 60),
            ],
          }),
          ...iibFields.map(
            (item) =>
              new TableRow({
                children: [
                  createCell(item.field, false, 40),
                  createCell(item.value || "-", false, 60),
                ],
              })
          ),
        ],
      })
    );
  });

  return elements;
}
